name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Or 'master', check your branch name

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # THIS STEP INJECTS THE SECRETS
      - name: Inject Secrets
        run: |
          sed -i "s|REPLACE_TEST_KEY|${{ secrets.TEST_VARIABLE }}|g" catalog.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
